debug = false

[grpc]
address = "0.0.0.0"
port = 50051

[http]
address = "0.0.0.0"
port = 8080

[metrics]
push_interval_seconds = 5
remote_write_url = "http://localhost:8428/api/v1/import/prometheus"
